import React,{ReactNode} from 'react'
import Header from './Header/Header'
import Footer from './Footer/Footer'
import Head from 'next/head'

export interface LayoutProps{
    children: ReactNode
}

const Layout  = ( {children}: LayoutProps ) =>{

    return (
        <div className="container">
            <Head>
                <title>Bidu E-commerce</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>   
            <div>{children}</div>
            <Footer/>
        </div>
    )
}
export default Layout